### ISSUE TITLE
Update for RAPIDS C++ wheels

### ISSUE THREAD

**Issue by vyasr** [rapidsai/ci-imgs#138]
Once https://github.com/rapidsai/build-planning/issues/33 is complete, we will have a new set of wheels that change some of the requirements of our CI images. This issue is to keep track of such changes as we discover them so that we can make them all at the end.

- [x] We will no longer need to install UCX into the images since UCX will be available as a wheel.
  - #154
- [ ] We will need to install the wheel Python package in addition to auditwheel because for the header-only C++ libraries the wheels won't contain any binaries, so auditwheel will be a no-op (`auditwheel repair` will not retag wheels that have no binaries to repair).
- #215

**Comment by jameslamb** [comment]
> *We will no longer need to install UCX into the images since UCX will be available as a wheel.*

Just noting this is done: #154

I've updated the description of this issue.

**Comment by bdice** [comment]
@vyasr Is there still work needed here? It seems like we have shipped librmm and libcudf wheels already so I am questioning what actions are needed, if any.

**Comment by vyasr** [comment]
We need to add `wheel` to the list of dependencies to install [here](https://github.com/rapidsai/ci-imgs/blob/main/ci-wheel.Dockerfile#L154). After that, I'm happy to close this issue and track other changes in one-off issues if you'd prefer.
