### ISSUE TITLE
Install AWS CLI v2

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/ci-imgs#28]
The version of the `aws` CLI tool that we install from `conda-forge` is `v1` ([src](https://anaconda.org/conda-forge/awscli)).

There is an open issue in the feedstock repo to support `v2` ([link](https://github.com/conda-forge/awscli-feedstock/issues/828)), but it seems that there are some obstacles.

Since `v2` has been out for nearly three years ([link](https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/)), we should strive to upgrade our image to use the latest version.

In lieu of a `conda` package, it seems that we can simply copy the necessary files from the official AWS CLI images:

- images - https://hub.docker.com/r/amazon/aws-cli
- dockerfile - https://github.com/aws/aws-cli/blob/v2/docker/Dockerfile

If we copy from their docker image using the line below (untested), it also gives us the added benefit of having the package version managed by Renovate.

```docker
COPY --from=amazon/aws-cli:2.9.8 /aws-cli-bin/ /usr/local/bin/
```

It might be worth installing other dependencies like this also. This way they're independent of the `conda` environment and managed by Renovate.

**Comment by ajschmidt8** [comment]
I did some local testing and the resulting images were quite a bit larger when installing from the DockerHub images via `copy` (see sizes below).

```
CentOS
installing from docker image    1.61GB
installing from conda           1.54GB

Ubuntu
installing from docker image    1.78GB
installing from conda           1.71GB

```

Therefore it's probably best just to wait for `conda` to support `v2` (see issue below) so that we don't inflate our image sizes more than we need to.

- https://github.com/conda-forge/awscli-feedstock/issues/828

**Comment by bdice** [comment]
awscli v2 is available for linux64 but not aarch64. I opened a PR to rebuild awscli 2 with arch support: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4993

**Comment by ajschmidt8** [comment]
linking this PR for posterity: https://github.com/rapidsai/ci-imgs/pull/82
